#!/bin/bash

cd "$(dirname "`readlink -f "$0"`")"
export SCRIPTS_PATH="$(pwd)"

fatal () {
    echo "Fatal error!"
    exit 1
}

if [[ $1 == tkg ]] ; then
    version="$2"
    if [[ -z $version ]] ; then
        echo "Use: 02_get_wine tkg VESRION"
        exit 0
    fi
    git clone https://github.com/Kron4ek/wine-tkg "${SCRIPTS_PATH}/wine-tkg/"
    pushd "${SCRIPTS_PATH}/wine-tkg/" || fatal
    rm -fr .git
    git init
    git add .
    git commit -m "Commit before patches."
    echo -e "-----------------------------------------\nAdding 001-wine-tkg-to-lg patches:"
    patch -Np1 < ../patches/001-wine-tkg-to-lg.patch || fatal

    popd || fatal
elif [[ $1 == tkg-ntsync ]] ; then
    git clone https://github.com/Kron4ek/wine-tkg wine -b ntsync
    mv -f "${SCRIPTS_PATH}/wine" "${SCRIPTS_PATH}/wine-tkg-ntsync"
    pushd "${SCRIPTS_PATH}/wine-tkg-ntsync/" || fatal
    rm -fr .git
    git init
    git add .
    git commit -m "Commit before patches."
    echo -e "-----------------------------------------\nAdding 001-wine-tkg-to-lg patches:"
    patch -Np1 < ../patches/001-wine-tkg-to-lg.patch || fatal

    popd || fatal
elif [[ $1 == ge ]] ; then
    if [[ ! -d "${SCRIPTS_PATH}/proton-ge" ]] ; then
        version="$2"
        if [[ -z $version ]] ; then
            echo "Use: 02_get_wine ge VESRION (X-X)"
            exit 0
        fi
        git clone --branch "GE-Proton$version" --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom || fatal
        mv "${SCRIPTS_PATH}/proton-ge-custom/wine" "${SCRIPTS_PATH}/proton-ge" || fatal
        pushd "${SCRIPTS_PATH}/proton-ge-custom" || fatal
        git log -1 | grep GE-Proton | awk -F'GE-Proton' '{print $2}' | awk '{print $1}' > ${SCRIPTS_PATH}/proton-ge/GE_VER || fatal
        popd || fatal
        rm -fr "${SCRIPTS_PATH}/proton-ge-custom" || fatal

        cd "${SCRIPTS_PATH}/proton-ge" || fatal
        rm -fr .git
        git init
        git add .
        git commit -m "Commit before patches."
    fi

    cd "${SCRIPTS_PATH}/proton-ge" || fatal

    echo -e "-----------------------------------------\nAdding De-steamify-proton-s-WINE_for_PortProton patches:\n"
    patch -Np1 < ../patches/proton-ge-to-lg-9-27.patch
else
    echo "Use: 02_get_wine < tkg | tkg-ntsync | ge >"
    exit 0
fi

echo -e "\nDone\n"

# ${SCRIPTS_PATH}/03_build_wine_debian_multi.sh
